
/* Oct 23, 2012*/
PFNGLACTIVETEXTUREPROC				glActiveTexture;
PFNGLATTACHSHADERPROC				glAttachShader;
PFNGLBINDBUFFERPROC					glBindBuffer;
PFNGLBINDTEXTUREPROC				glBindTexture;
PFNGLBUFFERDATAPROC					glBufferData;
PFNGLCLEARCOLORPROC					glClearColor;
PFNGLCLEARDEPTHPROC					glClearDepth;
PFNGLCLEARPROC						glClear;
PFNGLCOMPILESHADERPROC				glCompileShader;
PFNGLCREATEPROGRAMPROC 				glCreateProgram;
PFNGLCREATESHADERPROC 				glCreateShader;
PFNGLDELETESHADERPROC				glDeleteShader;
PFNGLDEPTHFUNCPROC					glDepthFunc;
PFNGLDETACHSHADERPROC				glDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC	glDisableVertexAttribArray;
PFNGLDRAWARRAYSPROC					glDrawArrays;
PFNGLDRAWELEMENTSPROC				glDrawElements;
PFNGLENABLEPROC						glEnable;
PFNGLENABLEVERTEXATTRIBARRAYPROC 	glEnableVertexAttribArray;
PFNGLGENBUFFERSPROC					glGenBuffers;
PFNGLGENTEXTURESPROC				glGenTextures;
PFNGLGETERRORPROC					glGetError;
PFNGLGETSHADERINFOLOGPROC			glGetShaderInfoLog;
PFNGLGETSHADERIVPROC				glGetShaderiv;
PFNGLGETSTRINGPROC					glGetString;
PFNGLGETUNIFORMFVPROC				glGetUniformfv;
PFNGLGETUNIFORMLOCATIONPROC			glGetUniformLocation;
PFNGLLINKPROGRAMPROC				glLinkProgram;
PFNGLSHADERSOURCEPROC				glShaderSource;
PFNGLTEXIMAGE2DPROC					glTexImage2D;
PFNGLTEXPARAMETERIPROC				glTexParameteri;
PFNGLUNIFORM1IPROC					glUniform1i;
PFNGLUNIFORM2FPROC					glUniform2f;
PFNGLUSEPROGRAMPROC					glUseProgram;
PFNGLVERTEXATTRIBPOINTERPROC		glVertexAttribPointer;
PFNGLVIEWPORTPROC					glViewport;
PFNGLGETINTEGERVPROC				glGetIntegerv;
PFNGLUNIFORMMATRIX4FVPROC			glUniformMatrix4fv;

typedef HGLRC WINAPI (*PFNwglCreateContext)(HDC);
typedef BOOL WINAPI (*PFNwglMakeCurrent)(HDC,HGLRC);
typedef PROC WINAPI (*PFNwglGetProcAddress)(LPCSTR);

PFNwglCreateContext MYwglCreateContext;
PFNwglMakeCurrent MYwglMakeCurrent;
PFNwglGetProcAddress MYwglGetProcAddress;
